### ISSUE TITLE
OpenCV(3.4.5) + DNN (-215:Assertion failed) separator_index < line.size() in function 'ReadDarknetFromCfgStream'

### ISSUE THREAD

**Issue by joaopalma5** [tahaemara/yolo-custom-object-detector#1]
python3 yolo_opencv.py -c custom/yolov3-tiny.cfg -w backup/yolov3-tiny_120000.weights -cl custom/objects.names 
['bola']
Traceback (most recent call last):
  File "yolo_opencv.py", line 47, in <module>
    net = cv2.dnn.readNet(args.weights,args.config)
cv2.error: OpenCV(3.4.5) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:507: error: (-215:Assertion failed) separator_index < line.size() in function 'ReadDarknetFromCfgStream'

I have this error on try your code... In darknet we can Run inference, and get results. You know the reason?

**Comment by tahaemara** [comment]
Did you set the number of anchors to 6?. Tiny yolo uses 6 anchors instead of 9 anchors in case of normal Yolo [here](https://github.com/tahaemara/yolo-custom-object-detector/blob/afef9e2ab1fc91212a0206df3a06d23f4792e164/python/custom/yolov3-tiny.cfg#L178)

**Comment by ajaykaarthic** [comment]
I have set it to 6 and yet i get the error !,  how can i resolve this?
![Screenshot from 2019-09-15 16-50-34](https://user-images.githubusercontent.com/33996820/64920794-f97ae780-d7d8-11e9-9b8a-b8aae338c146.png)

**Comment by Rakhesh96** [comment]
Though i tried anchor values to be 6 and 9 still it is not working, the same error is being show ...kindly help me out @tahaemara 
![unnamed](https://user-images.githubusercontent.com/25658241/66892972-a4660780-f00a-11e9-9979-6252849b62a1.png)

**Comment by ADLTU** [comment]
Hi, if you are using mac I found that if you use the textEdit.app, it adds a few lines at the top(you can't see them unless you use another editor) that are causing an issue, simply remove them and it will be fine.

**Comment by gmatesunny** [comment]
I have set following in yolov3-tiny.cfg 

[yolo]
mask = 3,4,5
anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
classes=4
num=6
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1

[yolo]
mask = 0,1,2
anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
classes=4
num=6
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1

still I get the error:

Traceback (most recent call last):
  File "yolo_opencv.py", line 49, in <module>
    net = cv2.dnn.readNet(args.weights,args.config)
cv2.error: OpenCV(4.1.0) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:509: error: (-215:Assertion failed) separator_index < line.size() in function 'ReadDarknetFromCfgStream'

I have also checked whether any extra line is added. I am on Ubuntu 16.04
Suggest me what shall I do next?

**Comment by gmatesunny** [comment]
> Though i tried anchor values to be 6 and 9 still it is not working, the same error is being show ...kindly help me out @tahaemara
> ![unnamed](https://user-images.githubusercontent.com/25658241/66892972-a4660780-f00a-11e9-9979-6252849b62a1.png)

Did you able to solve the problem?

**Comment by gmatesunny** [comment]
> Did you set the number of anchors to 6?. Tiny yolo uses 6 anchors instead of 9 anchors in case of normal Yolo [here](https://github.com/tahaemara/yolo-custom-object-detector/blob/afef9e2ab1fc91212a0206df3a06d23f4792e164/python/custom/yolov3-tiny.cfg#L178)

This issue shall be reopened.

**Comment by DocGrenas** [comment]
I have the same problem

net = cv2.dnn.readNetFromDarknet(_net_weights_path, _net_cfg_path)
cv2.error: OpenCV(3.4.2) /opt/concourse/worker/volumes/live/9523d527-1b9e-48e0-7ed0-a36adde286f0/volume/opencv-suite_1535558719691/work/modules/dnn/src/darknet/darknet_io.cpp:511: error: (-215:Assertion failed) separator_index < line.size() in function 'ReadDarknetFromCfgFile'

Have any idea?

Please tell me more

**Comment by ADLTU** [comment]
@gmatesunny did you check what I said before, do that if you are using mac

**Comment by DocGrenas** [comment]
> @gmatesunny did you check what I said before, do that if you are using mac

HI. 
I am using Mac and I have checked your suggestion but i can not see the xtra lines.

I have run my program on Vstudio

Another suggestion ?

**Comment by gmatesunny** [comment]
@ADLTU : I checked and it doesn't have extra lines. I am using vscode as editor.

**Comment by ADLTU** [comment]
Please do this and send a screenshot.
<img width="473" alt="Screenshot 2020-01-07 at 23 27 25" src="https://user-images.githubusercontent.com/33955381/71937837-71fd1e00-31a5-11ea-8d7e-4e8b249f2275.png">

**Comment by DocGrenas** [comment]
Hi.

I am using the yolov3.cfg


![Screen Shot 2020-01-08 at 1 38 38 PM](https://user-images.githubusercontent.com/59627002/72009887-600a9200-321c-11ea-9b20-fe0a7e4f0772.png)

**Comment by ADLTU** [comment]
Hi it won’t appear there, I had the same problem open the file in terminal
and you’ll see.

Hadi

**Comment by bikramb98** [comment]
@DocGrenas Facing the exact same problem as this: 

net = cv2.dnn.readNetFromDarknet(_net_weights_path, _net_cfg_path)
cv2.error: OpenCV(3.4.2) /opt/concourse/worker/volumes/live/9523d527-1b9e-48e0-7ed0-a36adde286f0/volume/opencv-suite_1535558719691/work/modules/dnn/src/darknet/darknet_io.cpp:511: error: (-215:Assertion failed) separator_index < line.size() in function 'ReadDarknetFromCfgFile'

Have you managed to solve it? Thanks!

**Comment by MorshedBabu** [comment]
# Use absolute path, it would work. For example,
### For Loading Yolo
**net = cv2.dnn.readNetFromDarknet("/home/babu/darknet/cfg/yolov3-tiny.cfg","/home/babu/darknet/yolov3-tiny.weights")**
### For Loading image
**img = cv2.imread("/home/babu/darknet/data/dog.jpg")**

**Comment by pra-dan** [comment]
@MorshedBabu 
> # Use absolute path, it would work. For example,
> ### For Loading Yolo
> **net = cv2.dnn.readNetFromDarknet("/home/babu/darknet/cfg/yolov3-tiny.cfg","/home/babu/darknet/yolov3-tiny.weights")**
> 
> ### For Loading image
> **img = cv2.imread("/home/babu/darknet/data/dog.jpg")**

I get this
```
Failed to parse NetParameter file: ~/docker/tiny_yolo_dark/yolov2-tiny.cfg in function 'readNetFromDarknet'

```

**Comment by hrithikppawar** [comment]
> # Use absolute path, it would work. For example,
> ### For Loading Yolo
> 
> **net = cv2.dnn.readNetFromDarknet("/home/babu/darknet/cfg/yolov3-tiny.cfg","/home/babu/darknet/yolov3-tiny.weights")**
> ### For Loading image
> 
> **img = cv2.imread("/home/babu/darknet/data/dog.jpg")**


I did this but still getting the same error...
```python
config_path = '/home/rozer/dev/ML Projects/YOLO_Object_Detection/yolov3.cfg'
weight_path = '/home/rozer/dev/ML Projects/YOLO_Object_Detection/yolov3.weights'
net = cv2.dnn.readNetFromDarknet(config_path, weight_path)
```
```
cv2.error: OpenCV(4.4.0) /tmp/pip-install-t2n0bol9/opencv-python/opencv/modules/dnn/src/darknet/darknet_io.cpp:628: error: (-215:Assertion failed) separator_index < line.size() in function 'ReadDarknetFromCfgStream'

```
I tried all above steps, but nothing worked, can anyone help me with this... Thank You!

**Comment by fedeos** [comment]
Try using this yolov3.cfg file. You will have to unzip it first.

[yolov3.cfg.zip](https://github.com/tahaemara/yolo-custom-object-detector/files/5519095/yolov3.cfg.zip)

**Comment by LahiruPradeePSenadhiraLankeshwara** [comment]
> 
> 
> Try using this yolov3.cfg file. You will have to unzip it first.
> 
> [yolov3.cfg.zip](https://github.com/tahaemara/yolo-custom-object-detector/files/5519095/yolov3.cfg.zip)

Thank You it works

**Comment by ShashikatReddy** [comment]
Even i'm getting same error while performing prediction on trained YOLOv3 Tiny. I i have checked number of  anchor are 6 only.

Could someone help me on this please .

I have trained model in my virtual machine Ubuntu 20.04 

Command
darknet$ python3 yolo_opencv.py -c /home/ai/darknet/training/yolov3-tiny.cfg -w /home/ai/darknet/backup/yolov3-tiny_60000.weights -cl /home/ai/darknet/training/objects.names

Error

Traceback (most recent call last):
  File "yolo_opencv.py", line 47, in <module>
    net = cv2.dnn.readNet(args.weights,args.config)
cv2.error: OpenCV(4.2.0) ../modules/dnn/src/darknet/darknet_io.cpp:519: error: (-215:Assertion failed) separator_index < line.size() in function 'ReadDarknetFromCfgStream'

**Comment by fedeos** [comment]
Try with this yolov3-tiny.cfg file:
[yolov3-tiny.zip](https://github.com/tahaemara/yolo-custom-object-detector/files/5775622/yolov3-tiny.zip)

**Comment by sujitvasanth** [comment]
Thannks @fadeos your cfg file worked...for me...
i read the original cfg file downloaded from darknet website and it was a html file.....

**Comment by fedeos** [comment]
Great! I hope you can move on and complete your project.

**Comment by charlie6echo** [comment]
the Original file that is on pjreddie's repo has been corrupted, please refer this one [yolov3.cfg](https://drive.google.com/file/d/1T8eDNQxyF5JYLy1x6W2kbL6FDdd4H2M0/view?usp=sharing).

**Comment by andyrey** [comment]
Just check up your _.cfg_ file carefully. In my case, I accidentally removed **#** before word **Testing**. When transfer configuration file from training mode to testing one, we can do very simple error inadvertently.

**Comment by Vinod95-git** [comment]
I get the same error but I am using yolov4 model. Any suggestions please?

![image](https://user-images.githubusercontent.com/78753959/144228237-37976915-84e9-432c-b2a2-5a851bc3ebac.png)

**Comment by trabelsim** [comment]
I had the same issue and even trying with the new .cfg file did not work.
Have a look at the order of the argument You are providing!

OpenCv in its documentation states that the order of model and config arguments does not matter, HOWEVER in my case it did matter. First config file and then weights (for DarkNet).

This works for me:
  Net net = readNetFromDarknet(modelConf, modelWeig);

**Comment by smallbook** [comment]
I think this is due to a few `#` in the cfg file that you need to remove,
and try again,
it worked for me.

**Comment by Soroosh-N** [comment]
I think the problem is that **some of us are downloading the "PAGE OF FILE"**. not the file itself! I mean, for downloading the cfg file, don't use this link:
https://github.com/pjreddie/darknet/blob/master/cfg/yolov3.cfg
Instead, use this link (The exact same file. but its file address. not page address):
https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov3.cfg
Hope it works for you.

**Comment by K-GOKULAPPADURAI** [comment]
> Try with this yolov3-tiny.cfg file: [yolov3-tiny.zip](https://github.com/tahaemara/yolo-custom-object-detector/files/5775622/yolov3-tiny.zip)

ya that error gone but a new error came 

cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\darknet\darknet_io.cpp:933: error: (-213:The function/feature is not implemented) Transpose the weights (except for convolutional) is not implemented in function 'cv::dnn::darknet::ReadDarknetFromWeightsStream'

**Comment by Emyyr** [comment]
Hi ,

I tried this method and this solved my problem but I want to talk about another solution. Configs are not broken. This is my idea.  Just change your anchors from from your .cfg file. I put COCO anchors from yolov3-tiny.cfg  to my cfg and it worked for me. You can try this options:
1. Control your .cfg file (spaces, comments "#" )
2. Control batch and subdivision (batch=1, subdivisions=1). I am writing this but didn't try :) . Because yolov3-tiny.cfg's batch and subdivison like this.
3. Control your .cfg and .weight file path in your code.
4. Control your anchors. 

> Try with this yolov3-tiny.cfg file: [yolov3-tiny.zip](https://github.com/tahaemara/yolo-custom-object-detector/files/5775622/yolov3-tiny.zip)
