### ISSUE TITLE
When training on Yolov3 usage of CPU is high and GPU is low

### ISSUE THREAD

**Issue by JanezCim** [tahaemara/yolo-custom-object-detector#2]
Hello!
I have some trouble figuring out if I am doing my training on custom images correctly, because when I'm running the training this is what i see:
![training](https://user-images.githubusercontent.com/8426792/51672980-24f05e00-1fcd-11e9-8e8f-aa95b21a5d9d.png)
So my feeling is that training should be using much more of GPU RAM and not as much of CPU power. Also my nvidia-smi processes bar does not show any proceesses (but that might be another problem)

**My question would be: Is this normal behaviour and if not, what should I do to make Yolo training make use of GPU more?**

Im running Yolov3 training from inside docker, which I enter with:
`docker run --runtime=nvidia -it --rm --entrypoint "/bin/bash" --env DISPLAY=$DISPLAY -v /home/spacerobo/Documents/Git/yolo-custom-object-detector:/home yolo3-opencv-cuda
`

and from /home/python/ I start training with this command:
`/darknet/./darknet detector train DatasetStones/trainer.data DatasetStones/yolov3-tiny.cfg darknet53.conv.74`

The darknet Makefile first couple of lines look like this:
```
GPU=1
CUDNN=1
OPENCV=1
OPENMP=0
DEBUG=0
CUDA=1

``` 

And the Yolo config file first couple of relevant lines:
```
[net]
# Testing
batch=1
subdivisions=1
# Training
batch=64
subdivisions=16
width=416
height=416
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
burn_in=1000
max_batches = 500200
policy=steps
steps=400000,45000032
scales=.1,.1
```

My setup:
Nvidia GeForce GT 740, 2GB
Intel i5-4460 CPU
8GB RAM
Manjaro OS

**Comment by tahaemara** [comment]
It is strange behavior. Try to change `CUDNN=1`  to `CUDNN=0`, hope this solves the problem.
