### ISSUE TITLE
avg loss is too high while training of yolov3 tiny

### ISSUE THREAD

**Issue by mudassirej** [tahaemara/yolo-custom-object-detector#3]
i am using images of 640*480 pixels. my data is not too large and i used yolov3 tiny.cfg for training with darknet52.448 weight file not using any GPU.

i get very high avg loss from starting. i dont know why?

Region 16 Avg IOU: 0.544776, Class: 0.499554, Obj: 0.499566, No Obj: 0.499584, .5R: 0.625000, .75R: 0.000000,  count: 8
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.499721, .5R: -nan, .75R: -nan,  count: 0
Region 16 Avg IOU: 0.567904, Class: 0.499282, Obj: 0.499585, No Obj: 0.499586, .5R: 0.714286, .75R: 0.142857,  count: 7
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.499723, .5R: -nan, .75R: -nan,  count: 0
Region 16 Avg IOU: 0.528688, Class: 0.499494, Obj: 0.499567, No Obj: 0.499584, .5R: 0.500000, .75R: 0.000000,  count: 8
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.499722, .5R: -nan, .75R: -nan,  count: 0
Region 16 Avg IOU: 0.693195, Class: 0.499361, Obj: 0.499523, No Obj: 0.499583, .5R: 0.833333, .75R: 0.333333,  count: 6
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.499722, .5R: -nan, .75R: -nan,  count: 0
Region 16 Avg IOU: 0.575871, Class: 0.499474, Obj: 0.499555, No Obj: 0.499586, .5R: 0.833333, .75R: 0.166667,  count: 6
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.499720, .5R: -nan, .75R: -nan,  count: 0
Region 16 Avg IOU: 0.551334, Class: 0.499472, Obj: 0.499480, No Obj: 0.499583, .5R: 0.750000, .75R: 0.000000,  count: 8
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.499722, .5R: -nan, .75R: -nan,  count: 0
Region 16 Avg IOU: 0.600088, Class: 0.499542, Obj: 0.499506, No Obj: 0.499584, .5R: 0.800000, .75R: 0.000000,  count: 5
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.499721, .5R: -nan, .75R: -nan,  count: 0
Region 16 Avg IOU: 0.572092, Class: 0.499428, Obj: 0.499505, No Obj: 0.499584, .5R: 0.666667, .75R: 0.000000,  count: 6
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.499724, .5R: -nan, .75R: -nan,  count: 0
Region 16 Avg IOU: 0.553508, Class: 0.499499, Obj: 0.499542, No Obj: 0.499585, .5R: 0.875000, .75R: 0.000000,  count: 8
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.499720, .5R: -nan, .75R: -nan,  count: 0
Region 16 Avg IOU: 0.553497, Class: 0.499381, Obj: 0.499442, No Obj: 0.499584, .5R: 0.555556, .75R: 0.111111,  count: 9
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.499722, .5R: -nan, .75R: -nan,  count: 0
Region 16 Avg IOU: 0.580341, Class: 0.499422, Obj: 0.499497, No Obj: 0.499584, .5R: 0.833333, .75R: 0.000000,  count: 6
Region 23 Avg IOU: 0.305393, Class: 0.499000, Obj: 0.499338, No Obj: 0.499720, .5R: 0.000000, .75R: 0.000000,  count: 1
Region 16 Avg IOU: 0.550048, Class: 0.499547, Obj: 0.499663, No Obj: 0.499584, .5R: 0.666667, .75R: 0.000000,  count: 3
Region 23 Avg IOU: 0.454548, Class: 0.499584, Obj: 0.499320, No Obj: 0.499721, .5R: 0.000000, .75R: 0.000000,  count: 1
Region 16 Avg IOU: 0.558823, Class: 0.499531, Obj: 0.499570, No Obj: 0.499583, .5R: 0.625000, .75R: 0.000000,  count: 8
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.499721, .5R: -nan, .75R: -nan,  count: 0
Region 16 Avg IOU: 0.615219, Class: 0.499384, Obj: 0.499519, No Obj: 0.499586, .5R: 1.000000, .75R: 0.000000,  count: 6
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.499723, .5R: -nan, .75R: -nan,  count: 0
Region 16 Avg IOU: 0.564179, Class: 0.499493, Obj: 0.499501, No Obj: 0.499588, .5R: 0.833333, .75R: 0.000000,  count: 6
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.499722, .5R: -nan, .75R: -nan,  count: 0
Region 16 Avg IOU: 0.546191, Class: 0.499529, Obj: 0.499633, No Obj: 0.499584, .5R: 0.571429, .75R: 0.000000,  count: 7
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.499721, .5R: -nan, .75R: -nan,  count: 0
1: 439.307251, 439.307251 avg, 0.000000 rate, 262.300388 seconds, 64 images
Loaded: 0.000048 seconds

and this is the avg loss and rate readings

1: 439.307251, 439.307251 avg, 0.000000 rate, 262.300388 seconds, 64 images
2: 437.796631, 439.156189 avg, 0.000000 rate, 260.419217 seconds, 128 images
3: 436.743683, 438.914948 avg, 0.000000 rate, 263.185402 seconds, 192 images
4: 439.118439, 438.935303 avg, 0.000000 rate, 260.007587 seconds, 256 images
5: 440.381744, 439.079956 avg, 0.000000 rate, 261.064861 seconds, 320 images
6: 437.774689, 438.949432 avg, 0.000000 rate, 259.742917 seconds, 384 images
7: 438.066528, 438.861145 avg, 0.000000 rate, 257.299960 seconds, 448 images
8: 439.212860, 438.896301 avg, 0.000000 rate, 257.397450 seconds, 512 images
9: 438.903320, 438.897003 avg, 0.000000 rate, 258.272195 seconds, 576 images
10: 438.605133, 438.867828 avg, 0.000000 rate, 257.986108 seconds, 640 images
11: 383.567566, 433.337799 avg, 0.000000 rate, 217.779761 seconds, 704 images
12: 385.344147, 428.538422 avg, 0.000000 rate, 217.042249 seconds, 768 images
13: 383.292480, 424.013824 avg, 0.000000 rate, 217.776042 seconds, 832 images
14: 384.244659, 420.036896 avg, 0.000000 rate, 217.518784 seconds, 896 images
15: 383.643707, 416.397583 avg, 0.000000 rate, 217.775383 seconds, 960 images
16: 382.793121, 413.037140 avg, 0.000000 rate, 217.932038 seconds, 1024 images
17: 383.037781, 410.037201 avg, 0.000000 rate, 217.793683 seconds, 1088 images
18: 384.058350, 407.439331 avg, 0.000000 rate, 217.527402 seconds, 1152 images
19: 384.619659, 405.157349 avg, 0.000000 rate, 217.347416 seconds, 1216 images
20: 384.284943, 403.070099 avg, 0.000000 rate, 217.261834 seconds, 1280 images
21: 557.822144, 418.545288 avg, 0.000000 rate, 327.631583 seconds, 1344 images
22: 558.407227, 432.531494 avg, 0.000000 rate, 326.945323 seconds, 1408 images
23: 558.074524, 445.085785 avg, 0.000000 rate, 327.198063 seconds, 1472 images
24: 558.270020, 456.404205 avg, 0.000000 rate, 327.856426 seconds, 1536 images
25: 558.338806, 466.597656 avg, 0.000000 rate, 327.192073 seconds, 1600 images
26: 558.290649, 475.766968 avg, 0.000000 rate, 327.586775 seconds, 1664 images
27: 558.376099, 484.027893 avg, 0.000000 rate, 326.799530 seconds, 1728 images
28: 557.339539, 491.359070 avg, 0.000000 rate, 327.356004 seconds, 1792 images
29: 558.731384, 498.096313 avg, 0.000000 rate, 327.647542 seconds, 1856 images
30: 558.595276, 504.146210 avg, 0.000000 rate, 326.950869 seconds, 1920 images
31: 692.322754, 522.963867 avg, 0.000000 rate, 411.091572 seconds, 1984 images
32: 692.104065, 539.877869 avg, 0.000000 rate, 411.196345 seconds, 2048 images
33: 692.929993, 555.183105 avg, 0.000000 rate, 411.557181 seconds, 2112 images
34: 694.361206, 569.100891 avg, 0.000000 rate, 411.281385 seconds, 2176 images
35: 693.376526, 581.528442 avg, 0.000000 rate, 410.951036 seconds, 2240 images
36: 692.907471, 592.666321 avg, 0.000000 rate, 411.049841 seconds, 2304 images
37: 693.877014, 602.787415 avg, 0.000000 rate, 411.390684 seconds, 2368 images
38: 692.186951, 611.727356 avg, 0.000000 rate, 411.028736 seconds, 2432 images
39: 693.944397, 619.949036 avg, 0.000000 rate, 410.121289 seconds, 2496 images
40: 693.239868, 627.278137 avg, 0.000000 rate, 410.412040 seconds, 2560 images
41: 692.219482, 633.772278 avg, 0.000000 rate, 410.161699 seconds, 2624 images
42: 694.196045, 639.814636 avg, 0.000000 rate, 410.275656 seconds, 2688 images
43: 693.995300, 645.232727 avg, 0.000000 rate, 410.213628 seconds, 2752 images
44: 694.451599, 650.154602 avg, 0.000000 rate, 410.228155 seconds, 2816 images
45: 692.546448, 654.393799 avg, 0.000000 rate, 410.168366 seconds, 2880 images
46: 691.750488, 658.129456 avg, 0.000000 rate, 411.126075 seconds, 2944 images
47: 693.839478, 661.700439 avg, 0.000000 rate, 410.967428 seconds, 3008 images
48: 693.480652, 664.878479 avg, 0.000000 rate, 410.267494 seconds, 3072 images
49: 692.532898, 667.643921 avg, 0.000000 rate, 411.022943 seconds, 3136 images
50: 692.901367, 670.169678 avg, 0.000000 rate, 410.338903 seconds, 3200 images
51: 497.743286, 652.927063 avg, 0.000000 rate, 278.302808 seconds, 3264 images
52: 498.426666, 637.477051 avg, 0.000000 rate, 278.354224 seconds, 3328 images
53: 495.944183, 623.323792 avg, 0.000000 rate, 278.412660 seconds, 3392 images
54: 497.179016, 610.709290 avg, 0.000000 rate, 278.443549 seconds, 3456 images
55: 496.152832, 599.253662 avg, 0.000000 rate, 279.154921 seconds, 3520 images
56: 496.505615, 588.978882 avg, 0.000000 rate, 278.242445 seconds, 3584 images
57: 494.551849, 579.536194 avg, 0.000000 rate, 278.382127 seconds, 3648 images
58: 496.167511, 571.199341 avg, 0.000000 rate, 278.240654 seconds, 3712 images
59: 495.463837, 563.625793 avg, 0.000000 rate, 278.398038 seconds, 3776 images
60: 497.070984, 556.970337 avg, 0.000000 rate, 278.684142 seconds, 3840 images
61: 384.408966, 539.714172 avg, 0.000000 rate, 217.767682 seconds, 3904 images
62: 385.864685, 524.329224 avg, 0.000000 rate, 217.507124 seconds, 3968 images
63: 383.937805, 510.290070 avg, 0.000000 rate, 217.256994 seconds, 4032 images
64: 383.163666, 497.577423 avg, 0.000000 rate, 217.012377 seconds, 4096 images
65: 383.387421, 486.158417 avg, 0.000000 rate, 217.972890 seconds, 4160 images
66: 382.984528, 475.841034 avg, 0.000000 rate, 217.588748 seconds, 4224 images
67: 385.618958, 466.818817 avg, 0.000000 rate, 217.499060 seconds, 4288 images
68: 382.405975, 458.377533 avg, 0.000000 rate, 217.634510 seconds, 4352 images
69: 385.127777, 451.052551 avg, 0.000000 rate, 217.618965 seconds, 4416 images
70: 382.505920, 444.197876 avg, 0.000000 rate, 217.654535 seconds, 4480 images
71: 623.082397, 462.086334 avg, 0.000000 rate, 351.220555 seconds, 4544 images
72: 623.486328, 478.226318 avg, 0.000000 rate, 351.498025 seconds, 4608 images
73: 623.361328, 492.739807 avg, 0.000000 rate, 351.219987 seconds, 4672 images
74: 622.147156, 505.680542 avg, 0.000000 rate, 351.685479 seconds, 4736 images
75: 625.195312, 517.632019 avg, 0.000000 rate, 351.314560 seconds, 4800 images
76: 623.505066, 528.219299 avg, 0.000000 rate, 351.449000 seconds, 4864 images
77: 623.507935, 537.748169 avg, 0.000000 rate, 351.963596 seconds, 4928 images
78: 621.648926, 546.138245 avg, 0.000000 rate, 351.101064 seconds, 4992 images
79: 622.835510, 553.807983 avg, 0.000000 rate, 351.297160 seconds, 5056 images
80: 623.368774, 560.764038 avg, 0.000000 rate, 351.290002 seconds, 5120 images
81: 286.198059, 533.307434 avg, 0.000000 rate, 157.447369 seconds, 5184 images
82: 287.941803, 508.770874 avg, 0.000000 rate, 157.684069 seconds, 5248 images
83: 285.415344, 486.435333 avg, 0.000000 rate, 157.401089 seconds, 5312 images
84: 285.205841, 466.312378 avg, 0.000000 rate, 157.329998 seconds, 5376 images
85: 285.281372, 448.209290 avg, 0.000000 rate, 157.584071 seconds, 5440 images
86: 287.431305, 432.131500 avg, 0.000000 rate, 157.354369 seconds, 5504 images
87: 286.164795, 417.534821 avg, 0.000000 rate, 157.275441 seconds, 5568 images
88: 286.064484, 404.387787 avg, 0.000000 rate, 157.955694 seconds, 5632 images
89: 286.444519, 392.593445 avg, 0.000000 rate, 157.526958 seconds, 5696 images
90: 287.335541, 382.067657 avg, 0.000000 rate, 158.285737 seconds, 5760 images
91: 554.981995, 399.359100 avg, 0.000000 rate, 329.371322 seconds, 5824 images
92: 553.158691, 414.739075 avg, 0.000000 rate, 326.247533 seconds, 5888 images
93: 555.990479, 428.864227 avg, 0.000000 rate, 326.451206 seconds, 5952 images
94: 554.330505, 441.410858 avg, 0.000000 rate, 326.310421 seconds, 6016 images
95: 554.205627, 452.690338 avg, 0.000000 rate, 326.317394 seconds, 6080 images
96: 553.398254, 462.761139 avg, 0.000000 rate, 326.462671 seconds, 6144 images
97: 554.518982, 471.936920 avg, 0.000000 rate, 327.193108 seconds, 6208 images
98: 555.916748, 480.334900 avg, 0.000000 rate, 326.842712 seconds, 6272 images
99: 553.823120, 487.683716 avg, 0.000000 rate, 327.115745 seconds, 6336 images
100: 552.513184, 494.166656 avg, 0.000000 rate, 326.454763 seconds, 6400 images
101: 619.286072, 506.678589 avg, 0.000000 rate, 352.168429 seconds, 6464 images
102: 617.514282, 517.762146 avg, 0.000000 rate, 352.174336 seconds, 6528 images
103: 618.645813, 527.850525 avg, 0.000000 rate, 352.396979 seconds, 6592 images
104: 617.819763, 536.847473 avg, 0.000000 rate, 352.473959 seconds, 6656 images
105: 617.598755, 544.922607 avg, 0.000000 rate, 353.036217 seconds, 6720 images
106: 617.861511, 552.216492 avg, 0.000000 rate, 352.430663 seconds, 6784 images
107: 617.363586, 558.731201 avg, 0.000000 rate, 353.301873 seconds, 6848 images
108: 617.079346, 564.566040 avg, 0.000000 rate, 353.166611 seconds, 6912 images
109: 616.639038, 569.773315 avg, 0.000000 rate, 353.929210 seconds, 6976 images
110: 615.588623, 574.354858 avg, 0.000000 rate, 352.950311 seconds, 7040 images
111: 281.859894, 545.105347 avg, 0.000000 rate, 157.596891 seconds, 7104 images
112: 282.193329, 518.814148 avg, 0.000000 rate, 157.864882 seconds, 7168 images
113: 283.582581, 495.290985 avg, 0.000000 rate, 157.756852 seconds, 7232 images
114: 282.969513, 474.058838 avg, 0.000000 rate, 157.587287 seconds, 7296 images
115: 281.781921, 454.831146 avg, 0.000000 rate, 158.565058 seconds, 7360 images
116: 281.244690, 437.472504 avg, 0.000000 rate, 157.544969 seconds, 7424 images
117: 280.310699, 421.756317 avg, 0.000000 rate, 157.605689 seconds, 7488 images
118: 280.991211, 407.679810 avg, 0.000000 rate, 157.815611 seconds, 7552 images
119: 281.158966, 395.027710 avg, 0.000000 rate, 157.860355 seconds, 7616 images
120: 281.178833, 383.642822 avg, 0.000000 rate, 158.100813 seconds, 7680 images
121: 327.148590, 377.993408 avg, 0.000000 rate, 195.432400 seconds, 7744 images
122: 326.496704, 372.843750 avg, 0.000000 rate, 195.366968 seconds, 7808 images
123: 327.663025, 368.325684 avg, 0.000000 rate, 195.394300 seconds, 7872 images
124: 325.546722, 364.047791 avg, 0.000000 rate, 194.875608 seconds, 7936 images
125: 324.472107, 360.090210 avg, 0.000000 rate, 195.080409 seconds, 8000 images
126: 325.627075, 356.643890 avg, 0.000000 rate, 194.862185 seconds, 8064 images
127: 326.404358, 353.619934 avg, 0.000000 rate, 194.930244 seconds, 8128 images
128: 324.869019, 350.744843 avg, 0.000000 rate, 195.257795 seconds, 8192 images
129: 324.588776, 348.129242 avg, 0.000000 rate, 195.362603 seconds, 8256 images
130: 325.526917, 345.869019 avg, 0.000000 rate, 194.918326 seconds, 8320 images
131: 278.576416, 339.139771 avg, 0.000000 rate, 158.724961 seconds, 8384 images
132: 277.433044, 332.969086 avg, 0.000000 rate, 158.295029 seconds, 8448 images
133: 278.286682, 327.500854 avg, 0.000000 rate, 157.998602 seconds, 8512 images
134: 278.139282, 322.564697 avg, 0.000000 rate, 158.167720 seconds, 8576 images
135: 277.541443, 318.062378 avg, 0.000000 rate, 159.111993 seconds, 8640 images
136: 277.136139, 313.969757 avg, 0.000000 rate, 158.650136 seconds, 8704 images
137: 278.575226, 310.430298 avg, 0.000000 rate, 158.221151 seconds, 8768 images
138: 276.459656, 307.033234 avg, 0.000000 rate, 158.083424 seconds, 8832 images
139: 276.105682, 303.940491 avg, 0.000000 rate, 158.015226 seconds, 8896 images
140: 277.102905, 301.256744 avg, 0.000000 rate, 158.623654 seconds, 8960 images
141: 536.659912, 324.797058 avg, 0.000000 rate, 326.846880 seconds, 9024 images
142: 538.147034, 346.132050 avg, 0.000000 rate, 326.141047 seconds, 9088 images
143: 535.919373, 365.110779 avg, 0.000000 rate, 326.283251 seconds, 9152 images
144: 534.371216, 382.036835 avg, 0.000000 rate, 327.150031 seconds, 9216 images
145: 535.093018, 397.342468 avg, 0.000000 rate, 326.926293 seconds, 9280 images
146: 534.861145, 411.094330 avg, 0.000000 rate, 326.816545 seconds, 9344 images
147: 534.762146, 423.461121 avg, 0.000000 rate, 327.129895 seconds, 9408 images
148: 533.693176, 434.484314 avg, 0.000000 rate, 327.121451 seconds, 9472 images
149: 531.593079, 444.195190 avg, 0.000000 rate, 327.136581 seconds, 9536 images
150: 531.298828, 452.905548 avg, 0.000001 rate, 327.194996 seconds, 9600 images
151: 414.923370, 449.107330 avg, 0.000001 rate, 257.420264 seconds, 9664 images
152: 415.928467, 445.789429 avg, 0.000001 rate, 257.910323 seconds, 9728 images
153: 413.900208, 442.600494 avg, 0.000001 rate, 257.637355 seconds, 9792 images
154: 412.858124, 439.626251 avg, 0.000001 rate, 257.096158 seconds, 9856 images
155: 412.618256, 436.925446 avg, 0.000001 rate, 257.430933 seconds, 9920 images
156: 411.467041, 434.379608 avg, 0.000001 rate, 257.970096 seconds, 9984 images
157: 409.170044, 431.858643 avg, 0.000001 rate, 259.011452 seconds, 10048 images
158: 410.271393, 429.699921 avg, 0.000001 rate, 258.337243 seconds, 10112 images
159: 406.555450, 427.385468 avg, 0.000001 rate, 257.326154 seconds, 10176 images
160: 408.599060, 425.506836 avg, 0.000001 rate, 258.188722 seconds, 10240 images
161: 461.562439, 429.112396 avg, 0.000001 rate, 281.067575 seconds, 10304 images
162: 459.650452, 432.166199 avg, 0.000001 rate, 281.043317 seconds, 10368 images
163: 456.708221, 434.620392 avg, 0.000001 rate, 281.593234 seconds, 10432 images
164: 454.844574, 436.642822 avg, 0.000001 rate, 281.670021 seconds, 10496 images
165: 454.015350, 438.380066 avg, 0.000001 rate, 287.939994 seconds, 10560 images
166: 453.958282, 439.937897 avg, 0.000001 rate, 289.653265 seconds, 10624 images
167: 452.909180, 441.235016 avg, 0.000001 rate, 295.676957 seconds, 10688 images
168: 450.827209, 442.194244 avg, 0.000001 rate, 286.917430 seconds, 10752 images
169: 449.469177, 442.921753 avg, 0.000001 rate, 290.520989 seconds, 10816 images
170: 447.693481, 443.398926 avg, 0.000001 rate, 286.509354 seconds, 10880 images

![Uploading training_loss_plot.png…]()
![3](https://user-images.githubusercontent.com/45818401/51720426-77db1b80-2088-11e9-8820-9e04a98d04a3.jpg)

**Comment by mudassirej** [comment]
![training_loss_plot](https://user-images.githubusercontent.com/45818401/51720444-93462680-2088-11e9-9e45-704a821dfdf3.png)
this is the avg loss graph

**Comment by tahaemara** [comment]
Try to check the match between objects in images and their corresponding boxes in text files.

**Comment by tphankr** [comment]
can you share a code to have the your 'avg loss graph". Thanks.
