### ISSUE TITLE
i have changed my object names but all it detect is "person"

### ISSUE THREAD

**Issue by wanghetongtt** [tahaemara/yolo-custom-object-detector#7]
![predictions](https://user-images.githubusercontent.com/26974450/55289474-3ec76c00-5395-11e9-9c67-64fb69261079.jpg)
i only have one class and it is called "Corrosion"
<img width="638" alt="Screen Shot 2019-03-31 at 9 14 26 AM" src="https://user-images.githubusercontent.com/26974450/55289485-661e3900-5395-11e9-8642-40b35eebb338.png">

**Comment by tahaemara** [comment]
can you provide me with a sample annotation file which contains something like this "0 0.780048 0.355769 0.430288 0.610577"?

**Comment by TestGithub19** [comment]
I faced same problem.I used your data and followed instructions. Please help me. I cound not figure out what i did wrong.
![predictions](https://user-images.githubusercontent.com/47893845/59980165-5bf08d00-95c8-11e9-9038-9238178e093d.jpg)
![Screenshot from 2019-06-23 15-03-02](https://user-images.githubusercontent.com/47893845/59980166-5bf08d00-95c8-11e9-9c41-210d664a8ba8.png)

I used this cmd for validation :./darknet detect custom/yolov3-tiny.cfg ../yolov3-tiny_1800.weights ../Dataset/images/nimage16.jpg

**Comment by tahaemara** [comment]
To solve this issue try to remove classes which exist in this file ../labelimg-master/data/predefined_classes.txt before annotating and then restart the labelimg.
or just edit "classes.txt" file in labels folder to remove the pre-defined classes.
