### ISSUE TITLE
Using Protobuff model files from Darknet/Darkflow in Java

### ISSUE THREAD

**Issue by dreistheman** [tahaemara/yolo-custom-object-detector#8]
Instead of .data model files generated from the DL4J training API, can we use .pb files from Darknet or Darkflow training to be used for inference. Basically, I already have my trained .pb file and I want to input it to the detection component of your tutorial (because it seems to be faster than Tensorflow's inference).

**Comment by tahaemara** [comment]
you can just use tensorflow and opencv to run your model, or just use opencv dnn module to load you model.

**Comment by tahaemara** [comment]
I think that you can easily import tensorflow models in java using javacpp "tensorflow presets"  https://medium.com/google-cloud/how-to-invoke-a-trained-tensorflow-model-from-java-programs-27ed5f4f502d
